### ISSUE TITLE
Error when adding a Projection Layout Element with a Shape layout

### ISSUE THREAD

**Issue by rmaessen** [OrchardCMS/Orchard#5270]
Tested on 1.9-int
1. Activate Projection Element module from Gallery
2. Add new Query with Content Type filter and Shape Layout with default settings
3. Attempt to add Projection Element with to a Page with the Shape as layout

This throws a "Shape type not found" error and does not allow me to add the Element to the Page. The layout works fine within a Projection Page or Projection Widget.

**Comment by sfmskywalker** [comment]
Fixed in #e810d885a0d7b7a2fda7b86b643237313b6e3437

**Comment by li0803** [comment]
Dear Developers,

still encounter this issue in 1.10. Do i take a wrong config? Below is my query's setting

![queryconfig](https://cloud.githubusercontent.com/assets/491759/17081734/42077f44-5196-11e6-9888-5aa1df0a6d7a.jpg)

**Comment by sfmskywalker** [comment]
Your shape name seems suspicious: "Content.DisplayUrl" is not a valid shape name. Make sure that you specify a valid shape name and that the shape exists in your theme.

**Comment by li0803** [comment]
I got the Shape name from the dropdown list of ShapType. I think it should be a valid shape name. 
![shapetypeselect](https://cloud.githubusercontent.com/assets/491759/17082144/88a0968e-51a5-11e6-9a2e-8da753afcb00.jpg)

I will try to check if it is in my theme. Thanks

**Comment by sfmskywalker** [comment]
I see. Actually, that is not a list of shapes, but a list of tokens. You should either type in the shape name yourself, or select a token that resolves to a valid shape name. The latter is not typically done and is a more advanced feature.
