### ISSUE TITLE
Layout - HTML Properties - cannot paste into text boxes

### ISSUE THREAD

**Issue by muzzi-w** [OrchardCMS/Orchard#5295]
In the new Layout editor, you cannot paste text into the HTML Properties text boxes. (maybe by design?)

**Comment by DanielStolt** [comment]
I seem to recall that we fixed this issue. @sfmskywalker? @muzzi-w which version/branch/commit are you on?

**Comment by sfmskywalker** [comment]
Can't recall that we did, only that we fixed the ability to type in spaces. In any case, I am able to reproduce this issue.

**Comment by muzzi-w** [comment]
Thanks Daniel & Spike for your prompt response.
I did a merge to and pull from 1.9_prod/1.9x and still the same problem. Nice that you have confirmed this issue.
Thanks to you both and the Orchard team for a great product.
Murray
http://objectmedia.com.au
