### ISSUE TITLE
After upgrade to 1.9 Widgets admin view renders very slow

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#5447]
After upgrade to 1.9 Widgets admin view renders very slow

**Comment by Piedone** [comment]
Already fixed in https://github.com/OrchardCMS/Orchard/commit/a7626b78f5aca8f67f6de8be2ffdcb4885a032c8.

**Comment by jersiovic** [comment]
Ups, I looked at branch 1.9.x I though if it is not solved there it was not solved. In order to avoid fixing something other has solved before me, which are the guidelines to knows what is expected to find on each branch. In which branch should I fix bugs?
