### ISSUE TITLE
Build error (ClickToBuild.cmd and VS2015)

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#5649]
I cloned master branch and replaced ClickToBuild.cmd from dev branch. I don't make any other changes.
I only have VS2015 installed. Now i get the following error when i run ClickToBuild.cmd:

```
Build FAILED.

"D:\Development\Source\orchard\Orchard.proj" (precompiled target) (1) ->
(ValidateProjectFiles target) ->
  D:\Development\Source\orchard\Orchard.proj(427,5): error : Error validating project file "D:\Development\Source\orchard\src\Orchard.Web\Modules\%2a%2a\%2a.csproj"
  D:\Development\Source\orchard\Orchard.proj(427,5): error : Illegal characters in path.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:01:35.35
```

What is the problem?

**Comment by sfmskywalker** [comment]
You seem to have a strangely named module project here: "\%2a%2a\%2a.csproj". Do you see it when you browse the Modules folder with Windows Explorer?

**Comment by bleroy** [comment]
Yes, either you did make other changes, or your installation went corrupt.

**Comment by armanforghani** [comment]
As i mentioned above "I don't make any other changes". There is no such module.
Also I think this is not a module name. It is ```"\**\*.csproj"```

Please look at the following section in Orchard.proj

```
<!-- ValidateProjectFiles-->
  <Target Name="ValidateProjectFiles">
    <CallTarget Targets="CompileMsBuildTasks"/>

    <ItemGroup>
      <Validate-ProjectFiles 
        Include="$(ModulesSrcFolder)\**\*.csproj;$(ThemesSrcFolder)\**\*.csproj;$(OrchardCoreSrcFolder)\Orchard.Core.csproj"
        Exclude="$(ModulesSrcFolder)\**\*.Specs.csproj"
        />
    </ItemGroup>

    <ValidateExtensionProjectFiles Files="@(Validate-ProjectFiles)"/>

  </Target>
```

I think there are some build issues that may be related to node_modules folder and Gulp and long path.

**Comment by jvdonkoec** [comment]
I can confirm that the node_modules in the DynamicForms and Layout modules is causing this error.

Removing the node_modules folders prior to building (ClickToBuild.cmd) Orchard solves this build error.

**Comment by DanielStolt** [comment]
This has been fixed in both 1.9.x and dev, and will be in upcoming releases.

**Comment by armanforghani** [comment]
@jvdonkoec, you are right as i mentioned above.
@DanielStolt, Thank you so much for fixing this issue. I read your useful article for this issue.
But i think the Orchard user should be able to build current stable release (1.9.1).
I hope the Orchard team releases next stable release 1.9.2 as soon as possible.
This issue will disappoint new users from using Orchard CMS.

**Comment by TwistedWhisper** [comment]
I'm still encountering the same problem with the dev. Only with the removal of the node_modules folder from Orchard.Layouts and Orchard.DynamicForms, does it build without errors.

**Comment by DanielStolt** [comment]
@TwistedWhisper The `node_modules` folders in those modules are no longer created, most likely you have them from before this was fixed. On a new clone you won't see this happening anymore.

**Comment by TwistedWhisper** [comment]
You are right. The `package.json` and `gulpfile.js` have been removed so *GulpJS* is not used and the `node_modules` won't be created. Doesn't this also mean that it is not recommended to use *gulp* with Orchard since the `node_modules` folder interferes with the build/deployment process?

From the looks of it, the problem is with Orchard.proj at line `<ValidateExtensionProjectFiles Files="@(Validate-ProjectFiles)"/>` which corresponds to the source codes at Orchard/src/Tools/MSBuild.Orchard.Tasks/ValidateExtensionProjectFiles.cs.
If it could accept a parameter of excluded folders as well, it might prevent the `node_modules` folder from being validated and traversed. This way *GulpJS* can still be used without affecting MsBuild, no?

**Comment by DanielStolt** [comment]
@TwistedWhisper All the gulp stuff in Orchard has been moved up to the solution level. See #5450 for more information.

I recently pushed a change to `dev` to exclude `node_modules` from packaging in `Orchard.proj` - what commit from `dev` are you testing with?

**Comment by TwistedWhisper** [comment]
@DanielStolt Thanks for the link. Now I see the rationale behind what you did. I'm very new to GitHub (or Git for that matter). Been thinking within the box and looking at the wrong direction.
