### ISSUE TITLE
Difference between Orchard.jQuery and Orchard.Resources

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#6080]
What is the difference between the module Orchard.jQuery with module Orchard.Resources?
Both modules have the following plugins
jquery.cookie.js
jquery.cookie.min.js
jquery.fileupload.js
jquery.iframe-transport.js
jquery.iframe-transport.min.js
jquery.plugin.js
jquery.plugin.min.js
jquery.utils.js

**Comment by bleroy** [comment]
That's because Orchard.jQuery will disappear, no?

**Comment by asemandeveloper** [comment]
but don't work calendar in Date fields!

**Comment by sfmskywalker** [comment]
Orchard.jQuery is being deprecated in favor of Orchard.Resources (as you can tell from the LifecycleStatus field in the module manifest and that it's been moved to the Deprecated folder.

**Comment by sfmskywalker** [comment]
The calendar in the date field has been broken for a while, before I started on the Resources module, so I think its unrelated. But will check.

**Comment by DanielStolt** [comment]
@sfmskywalker Hmm, when I tested a new clone of `dev` 3 weeks ago the calendar pickers were working, so it must have broken after that then.

**Comment by sfmskywalker** [comment]
@DanielStolt Perhaps, but I saw it broken on an older Orchard version that doesn't have Orchard.Resources yet, same issue.

**Comment by sfmskywalker** [comment]
Wait, I misread what you said. Then yes, must have been broken somewhere in the last 3 weeks.

**Comment by DanielStolt** [comment]
@asemandeveloper I have fixed the calendar pickers in the new `Orchard.Resources` module now and removed the dependency on `Orchard.jQuery`. As @bleroy mentioned `Orchard.jQuery` is deprecated.

**Comment by glenreyes** [comment]
@DanielStolt calendar picker is still broken

![screen shot 2016-03-25 at 17 05 31](https://cloud.githubusercontent.com/assets/5915507/14041445/dcc403a8-f2ab-11e5-8507-b9cae1f7b4f7.png)

**Comment by DanielStolt** [comment]
@glenreyes Which version and which distribution (source vs. ZIP)?

If it's the 1.10 ZIP distribution then I suspect it might be because of #6648.

**Comment by DanielStolt** [comment]
Ah, that must be it.

**Comment by glenreyes** [comment]
Yup that's it.The fix is still not in included in 1.10 ZIP. Thanks.

**Comment by sebastienros** [comment]
I just checked the zip file and it contains jQuery. Is the issue because a file is missing, or the asset link is missing because the module is not enabled?

**Comment by DanielStolt** [comment]
@sebastienros This is about the missing CSS file. I too checked the ZIP file and the file is missing. See #6648.

**Comment by sebastienros** [comment]
ok, I thought it was limited to the module, but it the file is missing, then it's a bigger issue. Time to release 1.10.1.

**Comment by DanielStolt** [comment]
Yep - I consider 1.10 badly broken actually.

**Comment by sebastienros** [comment]
Fixed already for 1.10.1
