### ISSUE TITLE
Dependency in 1.10 of Orchard.jQuery = broken modules

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6393]
Dependency in 1.10 Orchard.jQuery
Which does not exist anymore. Tried to change it in Module.txt files in complaining modules to Orchard.Resources still cannot get any to work.
Issue #17 in IDeliverable widgets
Your module works really great up to 1.9.2 cannot get it to work with 1.9.3 or 1.10.
Could not get most non core modules to work in 1.10, "various errors", in 1.9.3 some I get working in 1.10

**Comment by sfmskywalker** [comment]
That module should still exist but marked as deprecated. Could it have been excluded from the packaged version by accident?

**Comment by sebastienros** [comment]
It's excluded, but not by accident, maybe something we shouldn't do, or have another package with it.

**Comment by sfmskywalker** [comment]
I like the idea of a separate "compatibility" package, but it seems easier to just keep the deprecated modules around for another release. Perhaps we could move them to a folder named "Deprecated" or "Compat" next to the "Modules" folder, now that we can configure multiple module folders.

**Comment by donaldboulton** [comment]
I am going to focus on 1.10 as it has some really nice new changes and improvements. Fixing modules to work with it though needs to be addressed.
The source of 1.10 shows Orchard.jQuary, Task Lease but not Rules all three were excluded from the Orchard.Web.zip.
Have got Microsoft Azure Media Services and Audit Trail Trimming Asking for Task Lease. Scripting still looking for Orchard.Rules. Non Core broken modules iDeliverable Widgets, Mofit.Social, All, "CKEditors broken", and Ace editor, with LatestTwitter, all not working and not being added as content types or parts. These are the only ones, "that I use", I could not get working after adding Orchard.jQuary to 1.10. Module authors need to be notified of breaking changes in 1.10 I am sure there is a lot that are not going to work with Orchard.jQuary missing.

**Comment by donaldboulton** [comment]
Fixed iDeliverable widgets and most all other old modues with.

Fixed in web config
a removed assembly because of VS 2015 build errors
`<remove assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`
Add

`<add assembly="System.Web.Enity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`

`<add assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`

Fixed Errors full null propagating operator is not available in C# 5. Please use language version 6 or greater.
[http://stackoverflow.com/questions/27968963/c-sharp-6-0-features-not-working-with-visual-studio-2015](url)
 iDeliverable Widgets and many others had this error
for `(CultureInfo.InvariantCulture))` in WidgetOutputCacheFilter.cs

VS 2015 4.5.1 or greater error fixed it by installing

Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform

iDeliverable and most other modules working in 1.10.

**Comment by EscapeVeloc1ty** [comment]
This is still a problem... No Good. Please Reopen.

Confirmed to be an issue with Release: Orchard v.1.10.2.0

**Comment by sfmskywalker** [comment]
For which module(s) are you seeing this issue still?

**Comment by EscapeVeloc1ty** [comment]
For all of the Review/Voting modules.

On Thu, Feb 15, 2018 at 12:31 AM, Sipke Schoorstra <notifications@github.com

**Comment by sfmskywalker** [comment]
Ah. But those are gallery modules and not supported as part of the core Orchard solution. You should reach out to the author of those modules on their corresponding project sites.

**Comment by EscapeVeloc1ty** [comment]
They may only be gallery modules, but if there isn't any built in
functionality offered by Orchard that serves this purpose. Then its a
feature that Orchard is lacking.

The developers contributed those modules over 6 years ago, they are gone.

**Comment by sfmskywalker** [comment]
Maybe so, but that is off-topic with regards to this ticket’s subject. Please feel free to open another issue if you think that voting and reviewing functionality should be part of core.

**Comment by EscapeVeloc1ty** [comment]
Ok thanks so much, bye.
